#!/usr/bin/env bash
# This script configures the nginx server to redirect /redirect_me to another page.

# Update package list and install nginx
sudo apt update
sudo apt install nginx -y

# Allow SSH and HTTP traffic through firewall
sudo ufw allow 22
sudo ufw allow 80
sudo ufw enable

# Create a basic HTML file
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Add redirection rule to nginx configuration
sudo sed -i '\#listen 80 default_server#a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Restart nginx service
sudo service nginx restart
