#!/usr/bin/env bash
# Script that installs Nginx server and sets up redirection

# Update the system and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Allow HTTP traffic
sudo ufw allow 'Nginx HTTP'

# Create the "Hello World!" index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure Nginx redirection
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html;
        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
}" | sudo tee /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
